# Copyright 2025 NVIDIA CORPORATION
# SPDX-License-Identifier: Apache-2.0

name: KAI Scheduler - Release
on:
  release:
    types:
      - created

env:
  DOCKER_REGISTRY: "ghcr.io/ardge-labs/kai-scheduler"

jobs:
  build-and-push:
    name: Build & Push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Extract package version
        run: |
          PACKAGE_VERSION=${GITHUB_REF_NAME}
          echo "PACKAGE_VERSION=$PACKAGE_VERSION" >> $GITHUB_ENV
          echo $PACKAGE_VERSION

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.4'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build helm chart
        run: |
          sed -i 's#registry/local/kai-scheduler#${{ env.DOCKER_REGISTRY }}#' deployments/kai-scheduler/values.yaml
          helm package ./deployments/kai-scheduler -d ./charts --app-version $PACKAGE_VERSION --version $PACKAGE_VERSION

      - name: Upload As Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: charts/kai-scheduler-${{ env.PACKAGE_VERSION }}.tgz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
